### ISSUE TITLE
Output HP-specific read names [Feature request] 

### ISSUE THREAD

**Issue by davidebolo1993** [twolinin/longphase#12]
Hi guys, 

thanks for the great work. I was just wondering if there is any chance you can add a flag to output haplotype-specific read names to a TSV (or whatever format you prefer) when running haplotag. This will ideally allows users to save time re-parsing the haplotagged BAM if one wants to extract haplotype-specific read names to "phase" outputs from other tools (for instance, methylation calls from Nanopolish).
Thanks,

Davide

**Comment by davidebolo1993** [comment]
Something like `samtools view haptag.bam | grep ‘HP:i:1’ | cut -f 1` works just fine. My thoughts are that we can avoid to read the tagged BAM again if those names are stored when reads are tagged (maybe by setting an additional flag). There is no need to hurry on this, I can do this easily with pysam or standard shell. Just wondering if this can be useful to the users.

Thanks

**Comment by ythuang0522** [comment]
I never played with Nanopolish for methylation phasing. May I know if it can completely ignore the haplotagged bam and only needs two lists of read names? If so this would make sense to me. The haplotagging stage is very time-consuming due to the need to adding the tags back to the bam. The output of read names without bam might be faster.

**Comment by ythuang0522** [comment]
Got it. Will spare time to implement this alternative output.

**Comment by ythuang0522** [comment]
The v1.1 haplotag implemented `--log` which outputs a tabular plain-text file for your needs. It stores the assigned haplotype ID (i.e., 1 or 2) for each read and related statistics.

**Comment by davidebolo1993** [comment]
Thanks !
