### ISSUE TITLE
conda release?

### ISSUE THREAD

**Issue by davidebolo1993** [twolinin/longphase#14]
Hi guys,

any chance this can be released on conda?

**Comment by ythuang0522** [comment]
Hi, the binary release should be portable in most systems without conflicts. Why do you still need conda installation?

**Comment by davidebolo1993** [comment]
This is not strictly necessary, but having a conda release is cool for integrating longphase into snakemake workflows. I've made a docker container, for the time being. But maybe you can consider this for a future release. Just a suggestion.

Thanks,

Davide
