### ISSUE TITLE
LongPhase Phase out-of-range issue

### ISSUE THREAD

**Issue by zhengzhenxian** [twolinin/longphase#16]
Thanks for the great tool! 

We would like to report an error that happened in Clair3 with LongPhase phase but not with whatshap. The error was reported at [HKU-BAL/Clair3#112](https://github.com/HKU-BAL/Clair3/issues/112). Much appreciated if any suggestion or comment on it, and pls let me know if you need more details, thanks!

**Comment by twolinin** [comment]
Hi @zhengzhenxian 

Thank you for the issue. This issue is caused by the following alignment in the bam file. This alignment has CIGAR for column 6 but no information for column 10. I have pushed a new version to handle this situation.

```
cca98b9e-206c-4a36-af9e-fc7e0ec79e75    2064    chr16   3203484 60      5634H436M1I249M1I32M1D5M1D45M1D19M2I154M3I3M3I17M1D293M1I55M2D161M1I34M1I177M1D3M1D5M1I146M1D194M1D17M1I76M1I326M2D1M1I101M1I12M1I49M1D109M1I60M2D188M1D92M1D78M1D144M2I3M2I3M1D56M1D220M1D16M27H       *       0       9264    *       *       AS:i:6754       MD:Z:448C77A1T50T137^G0C2T1^C45^G20T172^T294C51C1^CT158C0C212^G0G2^T104C46^T194^G0C17C400^AA73T0A0A1T0G0G0A27T54^G46T122^TC156T1A0C28^T92^C78^G50A99^G56^A220^G8C7      NM:i:74 SA:Z:chr3,160832957,+,3628S4296M32D1340S,60,77;chr11,40335868,+,7924S1340M6D,60,28;     cm:i:475        de:f:0.0177     ms:i:6763       nn:i:0  s1:i:2863       s2:i:336        tp:A:P
```
