### ISSUE TITLE
feature request: estimated phasing quality

### ISSUE THREAD

**Issue by jts** [twolinin/longphase#19]
Hi,

Thanks for longphase, I have been using it the last few weeks and am impressed with its speed and usability. My main use case is generating a haplotagged .bam file, for use in downstream analysis. Is it possible to add a tag to the bam record with an estimated "phasing quality" score (a phred-scaled estimate that the assigned phase is incorrect)? If not, it would be great to have simple matching statistics (number of heterozygous variants that the read covered, number consistent with h1/h2, etc) available to the user.

Thanks for considering,
Jared

**Comment by ythuang0522** [comment]
This's an interesting suggestion as we know quite a few regions are challenging for phasing. It should be good to provide this info. Simple statistics would be easier as we are not sure how to estimate the Phred-scaled quality properly.

**Comment by ythuang0522** [comment]
Forgot to mention that the haplotag provided a `--log` option which outputs a tabular file storing a few statistics for each read that you might be interested. We also added the Phasing Quality into the table at v1.3.
![image](https://user-images.githubusercontent.com/6086073/186718084-8ccd2a09-20fe-4011-b721-495155fbaa35.png)

**Comment by jts** [comment]
Thanks so much!
