### ISSUE TITLE
./longPhase: error while loading shared libraries: libdeflate.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yekaizhou** [twolinin/LongPhase#2]
the installation is running smoothly but jumped out this issue when running longphase.

**Comment by ythuang0522** [comment]
Hi, the error looks like zlib is not found. LongPhase depends on htslib which depends on [zlib](http://zlib.net). Can you check if zlib was installed. We will add this check during configuration.

**Comment by ythuang0522** [comment]
Hi, can you create a clean virtual env (e.g., conda env) for installation? We can't reproduce the error but suspect this might be due to automatic search of [libdeflate](https://github.com/ebiggers/libdeflate) during htslib configuration (see below). It would be better if you could confirm any previous installation of libdefalte.

```
--with-libdeflate
    Libdeflate is a heavily optimized library for DEFLATE-based compression
    and decompression.  It also includes a fast crc32 implementation.
    By default, ./configure will probe for libdeflate and use it if
    available.  To prevent this, use --without-libdeflate.
```

**Comment by mailmrcai** [comment]
I have the same issue, solved by setting the environment variable.
export LD_LIBRARY_PATH=" your libdeflate path containing the file libdeflate.so.0"
I wonder this is caused by makefile

**Comment by twolinin** [comment]
Hi @mailmrcai 

Thank you for your testing. I have some questions to ask here.
1. Did you download the longphase_linux-x64.tar.xz or did you use git clone to compile and execute LongPhase?
2. Did your environment have libdeflate installed before installing LongPhase?

Thanks
JH
