### ISSUE TITLE
No FORMAT/PS description in header in SV output VCF

### ISSUE THREAD

**Issue by tgong1** [twolinin/longphase#27]
Hi,

I found there is no line for PS tag in header of SV output VCF, while SNP output VCF has the line as below:
##FORMAT=<ID=PS,Number=1,Type=Integer,Description="Phasing set (typically the position of the first variant in the set)">

This cause many problems in my downstream steps. Do you have any idea why it happens? I have tried both version 1.2 and 1.4.
Any suggestion or idea will be appreciated!

Thank you for your time and help,
Tingting

**Comment by twolinin** [comment]
Hi @tgong1 

Can you help me check if there are any results in the SV output VCF using the following commands? I suspect the issue might be related to avoiding duplicate header definitions.
``` 
grep "#" your_SV.vcf | grep "ID=PS"
```

Thanks

**Comment by tgong1** [comment]
Hi,

Thank you for the quick reply.
Here is the result by running the command, and I believe this is the tag from the SV merging tool SURVIVOR, which we have used.
##FORMAT=<ID=PSV,Number=1,Type=String,Description="Previous support vector">

I can remove this tag in the SV input VCF, if it can help.....

Thank you,
Tingting

**Comment by twolinin** [comment]
Hi @tgong1 

This problem will be addressed in the next version update.

Thanks
