### ISSUE TITLE
writeResult ... Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yekaizhou** [twolinin/longphase#3]
Hi,

The parsing of chrom/contigs can perform normally, but when entering the stage of writing results, it will bump out segmentation fault.

I am using an HG001 8X ONT alignment file, along with the corresponding cuteSV and Clair3 called VCF files as the input of LongPhase.

**Comment by twolinin** [comment]
Hi,
Can you provide the commands and files you use?
Thanks.

**Comment by yekaizhou** [comment]
it turned out that the expected input vcf should not be compressed. thanks a lot.

**Comment by cjw85** [comment]
@twolinin I ran in to the same issue, it would be a nice feature to allow the input file to be a gzipped compressed VCF.

**Comment by ythuang0522** [comment]
@cjw85 Agreed. We will push a new version supporting gz VCF.

**Comment by ythuang0522** [comment]
The gzipped  VCF is now supported. Please download the latest version.

**Comment by cjw85** [comment]
Thanks @ythuang0522, I'll check it out.
