### ISSUE TITLE
obtaining status of all 28M CpGs

### ISSUE THREAD

**Issue by ilivyatan** [twolinin/longphase#33]
Hi,
I'm comparing the use of modkit and longphase modcall on Nanopore modified BAMs.
The modcall works well and provides a nice output format.
But I noticed that it contains only a small subset of the CpGs, and I think it's due to some thresholding options.
Which options should I set if I want to see all CpGs in the genome (or at least all that are covered by reads), and their methylation status, or %methylated reads?

Thanks!

**Comment by ythuang0522** [comment]
Please upgrade to v1.6 #46
