### ISSUE TITLE
modcall vcf compatibility with IGV viewer

### ISSUE THREAD

**Issue by ilivyatan** [twolinin/longphase#39]
Hi,
We've been using your tool a lot and are happy with a lot of the results.
Still, we run into issues as we go.
We've tried to import the VCF restul from modcall and the phased modified VCF as well.
The first loads, but doesn't show any of the variants. Are the MD and UD formats a consensus? 
The latter file type issues a warning during indexing with 'tabix', but the also loads to IGV without the 'No Variants Found' on the track.
(We think the warning is related to variants without a phase block which is left as '*', but we didn't finish this investigation).
Both files have only REF alleles and nothing in the ALT, perhaps this is why nothing appears in IGV?
We've tried just putting a dummy allele in the ALT (e.g. 'A'), but that didn't work either.
We've haplotagged the BAM and can use IGV to color by 5mC, and we though of using the VCF to focus on DMR variants.
Do you have another suggestion for viewing methylation results from modcall/phased on IGV?
Thanks!

**Comment by twolinin** [comment]
Hi @ilivyatan 

This issue will be addressed in the next update. In the meantime, you can replace the '.' in the ALT field of the VCF with 'N'.

thanks

**Comment by ythuang0522** [comment]
Please upgrade to the v1.6 #46
