### ISSUE TITLE
is it possible to parse SNP call sets produced other than deepvariant?

### ISSUE THREAD

**Issue by yekaizhou** [twolinin/LongPhase#4]
it seems longphase will treat unphased longshot output vcf files as already phased, and will not proceed further.

**Comment by twolinin** [comment]
> it seems longphase will treat unphased longshot output vcf files as already phased, and will not proceed further.

Hi yekaizhou,
It is allowed to re-phase a VCF now. Please clone the latest version.

**Comment by yekaizhou** [comment]
Hi, this time longshot results can be accepted, but raised error `terminate called after throwing an instance of 'std::invalid_argument'`

I am using the command like `LongPhase/longPhase phase -s hg001_longshot.vcf.gz -b HG001_NBT2018_Guppy_4.2.2.bam -o lp_001 -r hg38.no_alt.fa -t 40 --ont`
the data used is just 8X ONT aligned to hg38, and the SNP calling result using longshot default parameters.
HG001 ONT reads: `https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG001/nanopore/Guppy_4.2.2/HG001_NBT2018_Guppy_4.2.2.fastq.gz`
hg38 reference: `http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/HGSVC2/technical/reference/20200513_hg38_NoALT/hg38.no_alt.fa.gz`

**Comment by twolinin** [comment]
Hi,
Can you help me decompress hg001_longshot.vcf.gz into hg001_longshot.vcf and run the program once?

**Comment by yekaizhou** [comment]
thanks a lot. it worked out.

**Comment by ythuang0522** [comment]
Though it worked, we should note that 8x is really low coverage. >30x is usually recommended.
