### ISSUE TITLE
Write a haplotagged BAM

### ISSUE THREAD

**Issue by cjw85** [twolinin/longphase#6]
Very often after phasing variants its useful to create a BAM file with reads tagged as to which haplotype they belong, as in the [`whatshap haplotag` ](https://whatshap.readthedocs.io/en/latest/guide.html?highlight=haplotag#whatshap-haplotag-tagging-reads-by-haplotype-for-visualization) command. Running this tagging as a discrete process involves additional IO; would it be possible to add BAM read tagging as an additional feature to longphase?

**Comment by ythuang0522** [comment]
Yes. We are investigating how whatshap implemented this.

**Comment by ythuang0522** [comment]
@cjw85 The release version [v1.0](https://github.com/twolinin/longphase/releases/download/v1.0/longphase_linux-x64.tar.xz) can output haplotype-tagging reads via `haplotag`. Sufficient multithreads are better more speed. 8 threads: ~31 min. 16 threads: ~16 min. 32 threads: ~11 minutes.
`longphase_linux-x64 haplotag -s snp.vcf -b alignment.bam -t 32`
