### ISSUE TITLE
CRAM output for haplotag

### ISSUE THREAD

**Issue by leonschuetz** [twolinin/longphase#69]
Hello,

is it possible to output CRAM files instead of BAM files in `longphase haplotag`?
It seems that all steps/tools work fine with CRAMs as input, but I didn't find an option to for the haplotag output. This would be a nice feature since longread data tends to get big and most other tools work fine with CRAM

Best,
Leon

**Comment by ythuang0522** [comment]
Hi @leonschuetz, You are right we forgot to change the output format to CRAM if the inputted file is CRAM. This feature will be added in the next minor release.

**Comment by leonschuetz** [comment]
Sounds great, Thank You!

**Comment by ythuang0522** [comment]
The [v1.7.2](https://github.com/twolinin/longphase/releases/tag/v1.7.2) now supports cram output option.
