### ISSUE TITLE
Suggestion: Address README to accomodate for Sniffles 2

### ISSUE THREAD

**Issue by tuannguyen8390** [twolinin/longphase#7]
Hi dev,

Just a suggestion :), Sniffles 2 was released a few days ago, the 
`--num_reads_report -1` flag is now changed to `--output-rnames`. See [#288](https://github.com/fritzsedlazeck/Sniffles/issues/288)

I am able to phase my data using LongPhase with Sniffles 2. So I presume it would be nice if you can update the README to include the new flag. 

Many thanks,

Tuan

**Comment by ythuang0522** [comment]
Thank you for the information. The usage of sniffles2 has been added in README.
