### ISSUE TITLE
@PG tag for longphase haplotag

### ISSUE THREAD

**Issue by DavidStreid** [twolinin/longphase#71]
Is there support for adding the @PG tag to the haplotagged BAM? Thank you for creating this great tool!

**Current Behavior**
```
$ BAM=ONT_sample.bam
$ longphase haplotag \
  -r hg38.fa \
  -s ssc.phased.vcf \
  --sv-file sv.phased.vcf \
  -b ${BAM} \
  -t 8 \
  -o ONT_sample.phased \
  --log
$ samtools view -H ${BAM} | grep @PG # just shows alignment headers
@PG	ID:minimap2	PN:minimap2	CL:minimap2...
$ 
```

**Desired Behavior**
```
$ samtools view -H ${BAM} | grep @PG # Expecting the longphase line
@PG	ID:minimap2	PN:minimap2	CL:minimap2...
@PG	ID:longphase	PN:longphase	CL:longphase haplotag -r hg38.fa -s ssc.phased.vcf...   
```

**Comment by ythuang0522** [comment]
@DavidStreid Thanks for your suggestion. Will add the PG tag into bam header in the next release.

**Comment by DavidStreid** [comment]
Thank you very much!

**Comment by ythuang0522** [comment]
The [v1.7.2](https://github.com/twolinin/longphase/releases/tag/v1.7.2) adds the PG tag into bam header.

**Comment by DavidStreid** [comment]
Thanks for getting to this so quickly!
