### ISSUE TITLE
Strangly sorted haplotag output

### ISSUE THREAD

**Issue by leonschuetz** [twolinin/longphase#90]
Hello,

I saw a strange behaviour of `haplotag`: 
The order of chromosomes changes in the output file. It seems that the chromosomes are sorted lexicographically (chr1, chr10, ... , chr2, ...), but the order inside one chromosome seems to be correct. 

This leads to strange error especially in CRAM files (e.g. reporting no reads on whole chromosomes with `samtools view -c`)

A (re)sorting of the output file seems to solve the issue, but that shouldn't be necesary, if the input is already sorted.

Best,
Leon

**Comment by twolinin** [comment]
Hi @leonschuetz 

Haplotag is executed according to the chromosome order in the VCF header. If the chromosomes in VCF header are sorted lexicographically, the output BAM file will follow this order. Could you please check the VCF header?

Tthanks

**Comment by leonschuetz** [comment]
Hi @twolinin,

yes, you are right. The order in the input VCF was incorrect. Did not thought about that. After correctly sorting the VCF header it works.

Thank You,
Leon
